### ISSUE TITLE
Problem with bawn.py

### ISSUE THREAD

**Issue by Toplica001** [auspicious3000/deepbeam#4]
Hello, i have a simple question related to bawn.py script. In that script there is variable called bins which is not defined anywhere in the script but its used in a few places. I would like to know if that is some other variable, some of the arrays, or i just need to define bins as a number. Thank you in advance.

**Comment by auspicious3000** [comment]
That's the number of quantization levels, you can set it to 256 in this case.

**Comment by Toplica001** [comment]
Ok, thank you.
